# Generated by Django 5.0.3 on 2024-04-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Изображение')),
                ('view_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('at_published', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('at_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания блога')),
                ('is_published', models.BooleanField(default=False, verbose_name='Статус публикации')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
