# Generated by Django 5.0.3 on 2024-04-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_blog_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='at_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
