# Generated by Django 5.0.3 on 2024-04-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_alter_blog_at_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='at_published',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
