# Generated by Django 5.0.3 on 2024-04-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_alter_blog_at_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='at_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания блога'),
        ),
    ]
