# Generated by Django 5.0.3 on 2024-04-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_blog_at_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='at_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
