# Generated by Django 5.0.3 on 2024-03-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('periodicity', models.CharField(max_length=10, verbose_name='Периодичность')),
                ('at_last_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней попытки')),
                ('status_attempt', models.BooleanField(default=False, verbose_name='Статус')),
                ('answer_mail', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Описание настройки')),
                ('at_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала отправки')),
                ('at_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания отправки')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус')),
                ('periodicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailingApp.periodicity', verbose_name='Периодичность')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание рассылки')),
                ('client', models.ManyToManyField(to='mailingApp.client', verbose_name='Клиент')),
                ('massage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailingApp.massage', verbose_name='Сообщение')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailingApp.setting', verbose_name='Настройки рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
