# Generated by Django 5.0.3 on 2024-04-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата последней попытки')),
                ('status_attempt', models.BooleanField(default=False, verbose_name='Статус')),
                ('answer_mail', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_view', models.BooleanField(default=False, verbose_name='Просмотр всех клиентов')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'permissions': [('set_view', 'can view all clients')],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание рассылки')),
                ('periodicity', models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('yearly', 'ежегодно')], max_length=10, verbose_name='Периодичность')),
                ('at_start', models.DateTimeField(verbose_name='Дата начала отправки')),
                ('at_end', models.DateTimeField(verbose_name='Дата окончания отправки')),
                ('status', models.CharField(choices=[('launched', 'Запущена'), ('create', 'Создана'), ('completed', 'Завершена')], default='create', max_length=20, verbose_name='Статус')),
                ('next_run', models.DateTimeField(verbose_name='Дата и время отправки')),
                ('is_view', models.BooleanField(default=False, verbose_name='Просмотр всех рассылок')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('set_status', 'can change status'), ('set_view', 'can view all mailings')],
            },
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('is_view', models.BooleanField(default=False, verbose_name='Просмотр всех сообщений')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'permissions': [('set_view', 'can view all massage')],
            },
        ),
    ]
