# Generated by Django 5.0.3 on 2024-03-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicity',
            name='periodicity',
            field=models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('yearly', 'ежегодно')], max_length=10, verbose_name='Периодичность'),
        ),
    ]
