# Generated by Django 5.0.3 on 2024-04-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0002_remove_mailing_user_mailing_owner_massage_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_status', 'can change status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('create', 'Создана'), ('launched', 'Запущена'), ('completed', 'Завершена')], default='create', max_length=20, verbose_name='Статус'),
        ),
    ]
