# Generated by Django 5.0.3 on 2024-03-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0002_alter_periodicity_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Завершена'), ('launched', 'Запущена'), ('create', 'Создана')], max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
