# Generated by Django 5.0.3 on 2024-04-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0003_alter_mailing_options_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('set_view', 'can view all clients')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_status', 'can change status'), ('set_view', 'can view all mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'permissions': [('set_view', 'can view all massage')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='client',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='Просмотр всех клиентов'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='Просмотр всех рассылок'),
        ),
        migrations.AddField(
            model_name='massage',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='Просмотр всех сообщений'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершена'), ('launched', 'Запущена'), ('create', 'Создана')], default='create', max_length=20, verbose_name='Статус'),
        ),
    ]
