# Generated by Django 5.0.3 on 2024-03-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0003_alter_setting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailings',
            name='setting',
        ),
        migrations.AlterModelOptions(
            name='periodicity',
            options={'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
        migrations.RemoveField(
            model_name='periodicity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='periodicity',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='mailings',
            name='at_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания отправки'),
        ),
        migrations.AddField(
            model_name='mailings',
            name='at_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала отправки'),
        ),
        migrations.AddField(
            model_name='mailings',
            name='periodicity1',
            field=models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('yearly', 'ежегодно')], default=123, max_length=10, verbose_name='Периодичность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailings',
            name='status',
            field=models.CharField(blank=True, choices=[('launched', 'Запущена'), ('completed', 'Завершена'), ('create', 'Создана')], max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
