# Generated by Django 5.0.3 on 2024-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0004_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('create', 'Создана'), ('completed', 'Завершена'), ('launched', 'Запущена')], default='create', max_length=20, verbose_name='Статус'),
        ),
    ]
