# Generated by Django 5.0.3 on 2024-03-22 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0004_remove_mailings_setting_alter_periodicity_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Periodicity',
            new_name='Attempt',
        ),
        migrations.AddField(
            model_name='mailings',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailingApp.attempt', verbose_name='попытка'),
        ),
        migrations.AlterField(
            model_name='mailings',
            name='status',
            field=models.CharField(blank=True, choices=[('create', 'Создана'), ('completed', 'Завершена'), ('launched', 'Запущена')], max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
