# Generated by Django 5.0.3 on 2024-03-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0005_rename_periodicity_attempt_mailings_attempt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailings',
            old_name='periodicity1',
            new_name='periodicity',
        ),
        migrations.AlterField(
            model_name='mailings',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Завершена'), ('launched', 'Запущена'), ('create', 'Создана')], max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
