# Generated by Django 5.0.3 on 2024-04-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0005_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('launched', 'Запущена'), ('create', 'Создана'), ('completed', 'Завершена')], default='create', max_length=20, verbose_name='Статус'),
        ),
    ]
