# Generated by Django 5.0.3 on 2024-03-22 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0006_rename_periodicity1_mailings_periodicity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание рассылки')),
                ('periodicity', models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('yearly', 'ежегодно')], max_length=10, verbose_name='Периодичность')),
                ('at_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала отправки')),
                ('at_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания отправки')),
                ('status', models.CharField(blank=True, choices=[('create', 'Создана'), ('completed', 'Завершена'), ('launched', 'Запущена')], max_length=20, null=True, verbose_name='Статус')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailingApp.attempt', verbose_name='попытка')),
                ('client', models.ManyToManyField(to='mailingApp.client', verbose_name='Клиент')),
                ('massage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailingApp.massage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.DeleteModel(
            name='Mailings',
        ),
    ]
