# Generated by Django 5.0.3 on 2024-03-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0007_mailing_delete_mailings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='at_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='at_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала отправки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Завершена'), ('launched', 'Запущена'), ('create', 'Создана')], max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
