# Generated by Django 5.0.3 on 2024-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0010_remove_mailing_attempt_attempt_mailing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершена'), ('create', 'Создана'), ('launched', 'Запущена')], default='create', max_length=20, verbose_name='Статус'),
        ),
    ]
