# Generated by Django 5.0.3 on 2024-03-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailingApp', '0012_alter_mailing_at_end_alter_mailing_at_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершена'), ('create', 'Создана'), ('launched', 'Запущена')], default='create', max_length=20, verbose_name='Статус'),
        ),
    ]
